### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by shreddedbacon** [amazeeio/lagoon-cli#36]
**Is your feature request related to a problem? Please describe.**
When onboarding customers or projects, it would be good to be able to provide a file that describes how the customer/project should be configured

**Describe the solution you'd like**
I think something like this might work well
```
groups:
  - name: example-com
users:
  - user:
      email: usera@example.com
      sshkey: ~/usera.pub
    groups:
      - name: example-com
        role: owner
  - user:
      email: userb@example.com
      sshkey: ~/userb.pub
    groups:
      - name: example-com
        role: developer
projects:
  - name: example-com
    giturl: git@github.com:example/example-com.git
    openshift: 2
    branches: "master|develop|staging"
    productionenvironment: master
    groups:
      - example-com
```
Then a `lagoon import -I /path/to/file` would start it off
